#!/bin/sh

ack_initialize()
{
  package define \
    base_url "https://github.com/petdance/ack/tarball/${package_version}"
}

package_install()
{
  paths create "${source_path}/${package_dir}/bin" "${install_path}/bin"

  curl \
    -L http://betterthangrep.com/ack-standalone \
    -o "${source_path}/${package_dir}/bin/ack"

  ensure_files_are_executable "${source_path}/${package_dir}/bin/ack"

  cp -f  "${source_path}/${package_dir}/bin/ack" \
    "${install_path}/bin/ack"
}

