#!/bin/sh

unrar_prefetch()
{
  package define \
    file "unrarsrc-${package_version}.${archive_format}" \
    dir "unrarsrc-${package_version}"
}

unrar_configure()
{
  file replace \
    content "^DESTDIR=.*$" \
    with "DESTDIR=${install_path}" \
    in "makefile.unix"
}

unrar_postfetch()
{
  if [[ -d unrar ]]
  then
    mv unrar/* .
    rm -rf unrar
  fi
}

unrar_build()
{
  make --makefile makefile.unix
}

unrar_install()
{
  paths create "${install_path}/bin"
  file move "unrar" to "${install_path}/bin"
  file chmod 755 "${install_path}/bin/unrar"
}

