#!/bin/sh

tmux_initialize()
{
  package_definition \
    base_url "http://downloads.sourceforge.net/project/tmux/tmux/tmux-${package_version}"
}

tmux_configure()
{
  package_must_be_active "libevent"
  package_must_be_active "ncurses"

  configure_flags+=( --enable-static )

  #export CFLAGS="-I${active_path}/include"
  #export LDFLAGS="-L${active_path}/lib" #  -lresolv"

  package_configure
}
