#!/bin/sh

tmux_prefetch()
{
  package define \
    base_url "http://downloads.sourceforge.net/project/tmux/tmux/tmux-${package_version}"
}

tmux_configure()
{
  configure_flags+=( --enable-static )

  #export CFLAGS="-I${active_path}/include"
  #export LDFLAGS="-L${active_path}/lib" #  -lresolv"

  package_configure
}
