#!/bin/sh

siege_install()
{
  paths create recursive "${install_path}"/{bin,etc,var}

  file copy force from "doc/siegerc"  to "${install_path}/etc/siegerc"
  file copy force from "doc/urls.txt" to "${install_path}/etc/urls.txt"
  file copy force from "src/siege"    to "${install_path}/bin/siege"

  package make install
  package activate first
}

