#!/bin/sh

tmux_initialize()
{
  package_dependencies=( libevent )

  package_definition \
    base_url "http://downloads.sourceforge.net/project/tmux/tmux/tmux-${package_version}"
}

tmux_configure()
{
  package_must_be_active "libevent"

  # Ensure that libevent is in the search paths.
  export CFLAGS="-I${active_path}/include"
  export LDFLAGS="-L${active_path}/lib"

  package_configure
}
