#!/bin/sh

htop_initialize()
{
  os is linux || error "htop may only be installed on Linux at this time."
}

htop_prefetch()
{
  package_url "http://downloads.sourceforge.net/project/htop/htop/${package_version}/htop-${package_version}.tar.gz" # ?use_mirror=voxel
}
