#!/bin/sh

cat << Info
init_scripts_path: $(init_scripts_path)
os_machine_type:   $MACHTYPE
os_type:           $(os_type)
os_arch_type:      $(os_arch_type)
os_arch:           $(os_arch)
os_arch_capable:   $(os_arch_capable)
os_cpu_count:      $(os_cpu_count)
Info

if os_is_linux
then
  log "free_memory: $(free -m | head -2)"
fi
